# ZMK Studio Support
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Bluetooth Power Increase
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Experimental BLE features
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# マウス機能を有効にする
CONFIG_ZMK_MOUSE=y
